#pragma once
enum Color:unsigned short
{
	BLACK=0x0,
	BLUE=0x1,
	GREEN=0x2,
	CYAN=0x3,
	RED=0x4,
	MAGENTA=0x5,
	YELLOW=0x6,
	WHITE=0x7,
	BRIGHTBLACK = 0x8,
	BRIGHTBLUE = 0x9,
	BRIGHTGREEN = 0xa,
	BRIGHTCYAN = 0xb,
	BRIGHTRED = 0xc,
	BRIGHTMAGENTA = 0xd,
	BRIGHTYELLOW = 0xe,
	BRIGHTWHITE = 0xf,
	BACK_BLACK = 0x00,
	BACK_BLUE = 0x10,
	BACK_GREEN = 0x20,
	BACK_CYAN = 0x30,
	BACK_RED = 0x40,
	BACK_MAGENTA = 0x50,
	BACK_YELLOW = 0x60,
	BACK_WHITE = 0x70,
	BACK_BRIGHTBLACK = 0x80,
	BACK_BRIGHTBLUE = 0x90,
	BACK_BRIGHTGREEN = 0xa0,
	BACK_BRIGHTCYAN = 0xb0,
	BACK_BRIGHTRED = 0xc0,
	BACK_BRIGHTMAGENTA = 0xd0,
	BACK_BRIGHTYELLOW = 0xe0,
	VBRIGHTWHITE = 0xf0
};
using BackColor = Color;
using FrontColor = Color;